### ISSUE TITLE
同步几次后失败全是unHandled

### ISSUE THREAD

**Issue by Kllen-rain** [Wanxp/obsidian-douban#56]
console输出如下
```js
app.js:1 Uncaught DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.<anonymous> (app://obsidian.md/app.js:1:1133422)
    at t.saveFileCache (app://obsidian.md/app.js:1:1149629)
    at t.onCreateOrModify (app://obsidian.md/app.js:1:1147506)
    at t.onCreate (app://obsidian.md/app.js:1:1147031)
    at e.tryTrigger (app://obsidian.md/app.js:1:1064472)
    at e.trigger (app://obsidian.md/app.js:1:1064405)
    at t.trigger (app://obsidian.md/app.js:1:1132563)
    at t.onChange (app://obsidian.md/app.js:1:1122926)
    at e.trigger (app://obsidian.md/app.js:1:1112321)
    at e.<anonymous> (app://obsidian.md/app.js:1:1110393)
app.js:1 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.<anonymous> (app://obsidian.md/app.js:1:1133422)
    at e.<anonymous> (app://obsidian.md/app.js:1:1910508)
    at app://obsidian.md/app.js:1:235836
    at Object.next (app://obsidian.md/app.js:1:235941)
    at app://obsidian.md/app.js:1:234878
    at new Promise (<anonymous>)
    at v (app://obsidian.md/app.js:1:234623)
    at e.getLastVersionByPath (app://obsidian.md/app.js:1:1910399)
    at e.<anonymous> (app://obsidian.md/app.js:1:1908566)
    at app://obsidian.md/app.js:1:235836
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'frontmatter')
    at eval (plugin:obsidian-dict…nary-plugin:40:5196)
    at e.tryTrigger (app.js:1:1064472)
    at e.trigger (app.js:1:1064405)
    at t.trigger (app.js:1:1841754)
    at t.activeLeafEvents (app.js:1:1827721)
    at s (app.js:1:709926)
    at l (app.js:1:710032)
app.js:1 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.<anonymous> (app://obsidian.md/app.js:1:1133422)
    at e.<anonymous> (app://obsidian.md/app.js:1:1910508)
    at app://obsidian.md/app.js:1:235836
    at Object.next (app://obsidian.md/app.js:1:235941)
    at app://obsidian.md/app.js:1:234878
    at new Promise (<anonymous>)
    at v (app://obsidian.md/app.js:1:234623)
    at e.getLastVersionByPath (app://obsidian.md/app.js:1:1910399)
    at e.<anonymous> (app://obsidian.md/app.js:1:1908566)
    at app://obsidian.md/app.js:1:235836
app.js:1 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.<anonymous> (app://obsidian.md/app.js:1:1133422)
    at e.<anonymous> (app://obsidian.md/app.js:1:1910508)
    at app://obsidian.md/app.js:1:235836
    at Object.next (app://obsidian.md/app.js:1:235941)
    at app://obsidian.md/app.js:1:234878
    at new Promise (<anonymous>)
    at v (app://obsidian.md/app.js:1:234623)
    at e.getLastVersionByPath (app://obsidian.md/app.js:1:1910399)
    at e.<anonymous> (app://obsidian.md/app.js:1:1908566)
    at app://obsidian.md/app.js:1:235836
app.js:1 DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.<anonymous> (app://obsidian.md/app.js:1:1133422)
    at t.saveFileCache (app://obsidian.md/app.js:1:1149629)
    at t.<anonymous> (app://obsidian.md/app.js:1:1147985)
    at app://obsidian.md/app.js:1:235836
    at Object.next (app://obsidian.md/app.js:1:235941)
    at a (app://obsidian.md/app.js:1:234680)
app.js:1 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.<anonymous> (app://obsidian.md/app.js:1:1133422)
    at e.<anonymous> (app://obsidian.md/app.js:1:1910508)
    at app://obsidian.md/app.js:1:235836
    at Object.next (app://obsidian.md/app.js:1:235941)
    at app://obsidian.md/app.js:1:234878
    at new Promise (<anonymous>)
    at v (app://obsidian.md/app.js:1:234623)
    at e.getLastVersionByPath (app://obsidian.md/app.js:1:1910399)
    at e.<anonymous> (app://obsidian.md/app.js:1:1908850)
    at app://obsidian.md/app.js:1:235836
plugin:obsidian-dictionary-plugin:28 Error requesting synonyms for word desc No Synonym API selected/available
plugin:obsidian-dictionary-plugin:28 Error requesting synonyms for word currentDate No Synonym API selected/available
```

**Comment by Wanxp** [comment]
能否提供下模板，和同步时配置界面的截图
